### ISSUE TITLE
MS-Iss-1: Notification Channel is invalid

### ISSUE THREAD

**Issue by raybalingit** [Marketing-Suite/android-sdk#18]
Create a notification channel is invalid. The log shows that the crash is happening on this line:
https://github.com/Marketing-Suite/android-sdk/blob/master/EMSMobileSDK/src/main/java/experian/mobilesdk/NotificationReceiver.java#L113 whenever the notification payload title is empty

**Comment by samsamlh** [comment]
Hey @raybalingit ! 

Since Android Oreo, the notification channel title and description is displayed in your app notification settings, it allows the user to personalize the notification parameters for each type of notifications. 
The channel title can't be an empty string and the channel description is not mandatory. You shouldn't use the notification payload to fill these parameters but rather predefined strings. 

```
public static final String PREFS_NAME = "choose a name for your channel";

  // Since android Oreo notification channel is needed.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel channel = new NotificationChannel(channelId,
                    PREFS_NAME,
                    NotificationManager.IMPORTANCE_DEFAULT);

            notificationManager.createNotificationChannel(channel);
            mBuilder.setChannelId(channelId);
        }
```
